version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-mono
    working_directory: /wp-desktop
    steps:
      - checkout
      - run:  
          name: Setup calypso
          command: |
                  git submodule init
                  git submodule update
      - run:  
          name: Install nvm and calypso node version
          command: |
                  set +e  
                  NODE_VERSION=$(cat calypso/.nvmrc)       
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      - run:  
          name: Decrypt assets
          command: |
                  openssl aes-256-cbc -d -in resource/calypso/secrets.json.enc -out calypso/config/secrets.json -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/mac.p12.enc -out resource/certificates/mac.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/win.p12.enc -out resource/certificates/win.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
      - run: 
          name: Build sources
          command: |
                  source $HOME/.nvm/nvm.sh
                  npm install
                  cd calypso
                  npm install
                  cd ..
                  make build-source CONFIG_ENV=release
      - run: 
          name: Build Windows & Linux
          command: |
                  source $HOME/.nvm/nvm.sh
                  make package BUILD_PLATFORM=wl
      - store_artifacts:
            path: release
      - run: 
          name: Cleanup # we don't need to share all files with other jobs
          command: |
                  rm -rf desktop
                  rm -rf desktop-config
                  rm -rf docs

                  cd calypso
                  rm -rf bin
                  rm -rf client
                  rm -rf docs
                  rm -rf node_modules
                  rm -rf test
                  rm -rf build/.babel-server-cache/
      - persist_to_workspace:
          root: /wp-desktop/release
          paths:
            - .
#   build:
#       macos:
#         xcode: "9.0"
#       shell: /bin/bash --login -eo pipefail
#       working_directory: /Users/distiller/wp-desktop
#       steps:
#         # - attach_workspace:
#         #     at: /Users/distiller/wp-desktop/release
#         - checkout
#         - run:  
#             name: Setup calypso
#             command: |
#                     git submodule init
#                     git submodule update
#         - run:  
#             name: Install nvm and calypso node version
#             command: |
#                     set +e  
#                     NODE_VERSION=$(cat calypso/.nvmrc)       
#                     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                    
#                     export NVM_DIR="/Users/distiller/.nvm"
#                     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
#                     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
#         - run: 
#             name: Install dependencies
#             command: |
#                     # nvm --version
#                     pwd
#                     ls -al /Users/distiller/.nvm
#                     source /Users/distiller/.nvm/nvm.sh
#                     nvm 
#                     # nvm install $(cat calypso/.nvmrc)
#                     # npm install
#         - run: 
#             name: Build Mac
#             command: |
#                     source /Users/distiller/.nvm/nvm.sh
#                     make package BUILD_PLATFORM=m
#         - store_artifacts:
#             path: release
# workflows:
#   version: 2
#   build_and_package:
#     jobs:
#       - build
#       - mac:
#           requires:
#             - build