version: 2
jobs:
  build:
    docker:
      - image: electronuserland/builder:wine-mono
    working_directory: /wp-desktop
    steps:
      - checkout
      - run:  
          name: Setup calypso
          command: |
                  git submodule init
                  git submodule update
      - run:  
          name: Install nvm and calypso node version
          command: |
                  set +e  
                  NODE_VERSION=$(cat calypso/.nvmrc)       
                  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                  
                  export NVM_DIR="$HOME/.nvm"
                  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      - run:  
          name: Decrypt assets
          command: |
                  openssl aes-256-cbc -d -in resource/calypso/secrets.json.enc -out calypso/config/secrets.json -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/mac.p12.enc -out resource/certificates/mac.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
                  openssl aes-256-cbc -d -in resource/certificates/win.p12.enc -out resource/certificates/win.p12 -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"
      - run: 
          name: Build sources
          no_output_timeout: 60m
          command: |
                  source $HOME/.nvm/nvm.sh
                  npm install
                  cd calypso
                  npm install
                  cd ..
                  make build-source CONFIG_ENV=release
      - run: 
          name: Build Windows & Linux
          command: |
                  source $HOME/.nvm/nvm.sh
                  make package BUILD_PLATFORM=wl
      - persist_to_workspace:
          root: /wp-desktop
          paths:
            - .
  package:
      macos:
        xcode: "8.3.3"
      steps:
        - attach_workspace:
            at: /wp-desktop
        - run:  
            name: Install nvm and calypso node version
            command: |
                    set +e  
                    NODE_VERSION=$(cat calypso/.nvmrc)       
                    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh | bash
                    
                    export NVM_DIR="$HOME/.nvm"
                    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
                    [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
        - run: 
            name: Build Mac
            command: |
                    source $HOME/.nvm/nvm.sh
                    make package BUILD_PLATFORM=m
  artifacts:
      docker:
        - image: electronuserland/builder:wine-mono
      steps:
        - attach_workspace:
            at: /wp-desktop
        - store_artifacts:
            path: release

workflows:
  version: 2
  build_and_package:
    jobs:
      - build
      - mac:
          requires:
            - build
      - artifacts:
          requires: 
            - build
            - mac